/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as BSlugConfirmedRouteImport } from './routes/b.$slug.confirmed'
import { Route as ApiTwilioInboundRouteImport } from './routes/api.twilio.inbound'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api.stripe.checkout'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugConfirmedRoute = BSlugConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => BSlugRoute,
} as any)
const ApiTwilioInboundRoute = ApiTwilioInboundRouteImport.update({
  id: '/api/twilio/inbound',
  path: '/api/twilio/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/b/$slug/confirmed': typeof BSlugConfirmedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/b/$slug/confirmed': typeof BSlugConfirmedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/b/$slug/confirmed': typeof BSlugConfirmedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/b/$slug'
    | '/dashboard/bookings'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/twilio/inbound'
    | '/b/$slug/confirmed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/b/$slug'
    | '/dashboard/bookings'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/twilio/inbound'
    | '/b/$slug/confirmed'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/b/$slug'
    | '/dashboard/bookings'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/twilio/inbound'
    | '/b/$slug/confirmed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTwilioInboundRoute: typeof ApiTwilioInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/confirmed': {
      id: '/b/$slug/confirmed'
      path: '/confirmed'
      fullPath: '/b/$slug/confirmed'
      preLoaderRoute: typeof BSlugConfirmedRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/api/twilio/inbound': {
      id: '/api/twilio/inbound'
      path: '/api/twilio/inbound'
      fullPath: '/api/twilio/inbound'
      preLoaderRoute: typeof ApiTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface BSlugRouteChildren {
  BSlugConfirmedRoute: typeof BSlugConfirmedRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugConfirmedRoute: BSlugConfirmedRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BSlugRoute: BSlugRouteWithChildren,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTwilioInboundRoute: ApiTwilioInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
